kind: pipeline
type: docker

steps:
  - name: test
    image: python:3.11.8-alpine
    commands:
      - pwd
      - apk --no-cache add bash coreutils gcc make musl-dev
      - pip --version
      - pip --disable-pip-version-check install --requirement=requirements.txt --root-user-action=ignore
      - adduser --disabled-password --uid=1000 user
      - '[[ $CI_REPO_REMOTE ]] && chown --recursive user: .'
      - su user -c 'python3 template.py'
      - su user -c 'python3 -m unittest discover --start-directory=test --verbose'
      - su user -c 'yapf --version'
      - su user -c 'yapf --diff template.py test/test_template.py'
      - su user -c 'pylint --version'
      - su user -c 'pylint --verbose template.py test/test_template.py'
      - su user -c 'mypy --version'
      - su user -c 'mypy template.py test/test_template.py'
      - su user -c 'make clean'
